### ISSUE TITLE
Shared courses and progress displayed by subcourse

### ISSUE THREAD

**Issue by charybdescylla** [catalyst/moodle-mod_subcourse#40] opened 2020-08-26 09:49 UTC
Hello and thank you again for this fantastic tool for aggregating students' grades and progress from several modules into a meta course associated with a training.
Our particularity is that some modules are designed to be shared with several trainings (meta courses) and therefore several cohorts of students (groups at the module level). 
The modules therefore include common and some specific activities (with access conditions based on group membership).
At the module level it is possible to specify which activities are to be taken into account for the progression of each group. The percentage of progression correctly reflects the activities to be done for a group of students.
But in the meta-course, the progression returned by subcourse takes into account all the activities of the modules and in particular those specific to other courses using the module as well. 
For example, a module common to two meta-courses A and B may have 10 common activities and 2 different activities between groups A and B.
A and B therefore have 12 activities to complete in order to obtain 100% progress.
In the meta-course for students A, the progression is calculated on the basis of 14 (10+2+2) activities to be completed and not 12, which gives a result of less than 100%.
Is it possible to take into account the parameters of the progression blocks (which can be conditioned on belonging to a group) in the data transfer to the meta course via subcourse?

**Comment by mudrd8mz** [comment] 2020-08-26 11:48
Hello.

What block do you use in the subcourses to meassure the progress. Is it https://moodle.org/plugins/block_progress ?

**Comment by charybdescylla** [comment] 2020-08-26 12:24
Yes absolutely. It allows you to combine a profile of existing activities with a specific group of students.

**Comment by mudrd8mz** [comment] 2020-08-27 09:22
Yeah. I suspect the issue might be that while the Subcourses uses the Moodle core API to calculate the progress within the course, these other plugins do not and they implement their own way of calculating the progress.

Can you confirm that the Subcourse shows the same percentual progress as is reported on students' Dashboards?

**Comment by charybdescylla** [comment] 2020-08-27 14:33
Indeed, the completion of activities (in the sub-course management menu and not in the progress block) shows the same percentage as the one indicated in the student's dashboard (in the meta course).
Note that the progress block automatically calculates the progress according to the activities available to the user (it is not necessary to choose them manually), which indeed seems to indicate that the progress block plugin uses its own way of calculating progress.

**Comment by mudrd8mz** [comment] 2020-08-27 17:55
> as the one indicated in the student's dashboard (in the meta course)

Please note, by "Dashboard" I mean the site home page - https://docs.moodle.org/en/Dashboard - not the meta course. Do we refer to the same feature?

If so, I assume you will the same difference between the progress on the Dashboard and in the Progress bar block. The Subcourse should report same value as the Dashboard, by design.

**Comment by charybdescylla** [comment] 2020-08-29 08:25
Sorry, I didn't understand because by default in the student's dashboard there was no "progress" block.
By adding the block for our demo student, I see the same progression as in the sub-course, the one that takes into account the activities available for this student. 
The progress in the dashboard is updated correctly if I change the student's group and therefore the activities available to them in the sub-course.
On the other hand, in the meta-course that uses the sub-course plugin, the progress remains the same for the sub-course whatever the group assigned to the student. It seems to be calculated as the number of completed activities / total number of activities present in the sub-course. 
Hoping to have been clearer.

**Comment by mudrd8mz** [comment] 2020-09-03 07:45
I see. Thanks for the additional info. I'll try to reproduce it locally to see if there is something that can be done about it.

**Comment by mudrd8mz** [comment] 2020-09-22 10:05
I found https://tracker.moodle.org/browse/MDL-60912 and I suspect that actually explains the problem here. Am I right?

**Comment by charybdescylla** [comment] 2020-09-26 10:34
Indeed, I see that the community is already looking into the root of the problem. Thank you for your help. I will be closely following the discussions and will find an alternative solution to allow students to follow their progress in the sub-courses in the meantime.

**Comment by danmarsden** [comment] 2023-11-03 07:19
reading through this backlog it looks like this has been reported as an upstream Moodle issue (with a decent amount of votes) rather than subcourse so I'm closing this one off for now. - thanks!

**Closed by danmarsden** 2023-11-03 07:19 UTC
